using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace Softphone.Model
{
    public enum ResponseCode
    {
        ResponseWelcome = 100,
        ResponseConfiguration = 102,
        ResponseAgentLogin = 103,
        ResponseAgentNotReady = 105,
        ResponseAgentReady = 107,
        ResponseAgentLogout = 109,
        ResponseAgentAftercallWork = 111,
        ResponseExtensionUnregistered = 163,
        ResponseDtmfSent = 113,
        ResponseCallEstablished = 117,
        ResponseCallHeld = 125,
        ResponseCallDialing = 131,
        ResponseCallReleased = 137,
        ResponseCallRetrieved = 139,
        ResponseAddressInfo = 143,
        ResponseCallInfo = 145,
        ResponseLocationInfo = 147,
        ResponseUserEventSent = 149,
        ResponseUserDataChanged = 151,
        ResponseUserDataDeleted = 155,
        ResponseMuteOn = 157,
        ResponseMuteOff = 159,
        ResponseNetworkReached = 164,
        ResponseCallRinging = 141,
        ResponseLinkConnected = 200,
        ResponseExtensionRegistered = 202,
        ResponsePrimaryChanged = 204,
        ResponseDnBackInService = 206,
        ResponsePartyAdded = 208,
        ResponsePartyDeleted = 210,
        ResponsePartyChanged = 212,
        ResponseMaskedDtmfSent = 214,
        ResponseEnteredSecureModeSent = 216,
        ResponseExitedSecureModeSent = 218,
        ResponsePanResetSent = 220,
        ResponseCvcResetSent = 222,
        ResponseError = 001,
        ResponseNoMatchingPersonOrAgent = 311,
        ResponseNoMatchingExtension = 313,
        ResponseNoMatchingTserver = 315,
        ResponseDestinationBusy = 317,
        ResponseDnOutOfService = 319,
        ResponseSemafoneLoginFailed = 350,
        ResponseSemafoneEnterSecureModeFailed = 351,
        ResponseSemafoneListenForDtmfFailed = 352,
        ResponseSemafoneExitSecureModeFailed = 353,
        ResponseSemafoneResetPanFailed = 354,
        ResponseSemafoneResetCvcFailed = 355,
        ResponseSemafoneDpmtargetDown = 356,
        ResponseDenialOfService = 401,
        ResponseIgnoreEvent = 500
    }
    public enum RequestCode
    {
        RequestAgentLogin = 102,
        RequestAgentNotReady = 104,
        RequestAgentReady = 106,
        RequestAgentLogout = 108,
        RequestSendDtmf = 112,
        RequestAlternateCall = 114,
        RequestAnswerCall = 116,
        RequestCompleteConference = 120,
        RequestCompleteTransfer = 122,
        RequestCallHold = 124,
        RequestInitiateConference = 126,
        RequestInitiateTransfer = 128,
        RequestCallRelease = 136,
        RequestCallRetrieve = 138,
        RequestMakeCall = 130,
        RequestSingleStepTransfer = 140,
        RequestAddressInfo = 142,
        RequestCallInfo = 144,
        RequestLocationInfo = 146,
        RequestUserEvent = 148,
        RequestAttachUserData = 150,
        RequestUpdateUserData = 152,
        RequestDeleteUserData = 154,
        RequestMuteOn = 156,
        RequestMuteOff = 158,
        RequestPciEnterSecureMode = 160,
        RequestPciExitSecureMode = 162,
        RequestPciCollectDigits = 164,
        RequestPciPanReset = 166,
        RequestPciCvcReset = 168,
        RequestBrokerInformation = 910,
        RequestGracefulServerShutdown = 912,
        RequestHeartbeat = 500,
        ResponseError = 001,
        ResponseInvalidRequestMessage = 303,
        ResponseNoMatchingPersonOrAgent = 311,
        ResponseNoMatchingExtension = 313,
        ResponseNoMatchingTserver = 315,
        ResponseDestinationBusy = 317,
        ResponseDnOutOfService = 319,
        ResponseHardwareError = 321,
        ResponseLinkDisconnected = 323,
        ResponseSemafoneLoginFailed = 350,
        ResponseSemafoneEnterSecureModeFailed = 351,
        ResponseSemafoneListenForDtmfFailed = 352,
        ResponseSemafoneExitSecureModeFailed = 353,
        ResponseSemafoneResetPanFailed = 354,
        ResponseSemafoneResetCvcFailed = 355,
        ResponseServerShutdown = 501,
        ResponseBrokerInformation = 911,
        ResponseGracefulServerShutdownAcknowledged = 913,
        ResponseDenialOfService = 401,
        ResponseNoMatchingInformation = 301,
        ResponseConfigurationServerNotAvailable = 302,
        ResponseMissingRequiredHostname = 303,
        ResponseMissingRequiredDomainUsername = 304,
        ResponseShutdown = 501,
        ResponseManagementStatistics = 911
    }

    public enum AgentActionRequested
    {
        None = 0,
        Connect = 1,
        Ready = 2,
        NotreadyNormal = 3,
        Dialline1 = 4,
        Dialline2 = 5,
        Holdline1 = 6,
        Holdline2 = 7,
        Retrieveline1 = 8,
        Retrieveline2 = 9,
        Hangupline1 = 10,
        Hangupline2 = 11,
        Coldtransfer = 12,
        Warmtransfer = 13,
        Completewarmtransfer = 14,
        Initiateconference = 15,
        Completconference = 16,
        Togglelines = 17,
        Disconnect = 18,
        NotreadyOutbound = 19,
        Idv = 20,
        Muteline1 = 21,
        Muteline2 = 22,
        Unmuteline1 = 23,
        Unmuteline2 = 24

    }

    public enum AgentStates
    {
        Login = 1,
        NotreadyNormal = 2,
        Ready = 3,
        NotreadyOutbound = 4,
        Logout = 5
    }
}
